/**
 * COUNTRY NAMES FOR THE PHONE PICKER, as DATA — identical on the server and in the browser.
 *
 * They used to come from `Intl.DisplayNames` at render time. That is a platform API whose
 * answer depends on the ICU / CLDR build underneath it, and the server (Node) and the
 * browser (Chromium) do not agree for every country: Hong Kong, Macao, Palestine and the
 * Falkland Islands are spelled differently, in English and in Arabic. A `<select>` whose
 * option text differs between the server's HTML and the client's first render is a
 * hydration mismatch (React error #418) on every page that draws the field. Text that
 * is rendered on both sides must come from one source, so this is it.
 *
 * One entry per country `libphonenumber-js` can parse (`lib/contact/country-names.test.ts`
 * fails if that list grows). Names are the CLDR ones, with the four that differ between ICU builds
 * pinned to their short, common form. To regenerate after a dependency bump, print
 * `new Intl.DisplayNames([locale], { type: "region" }).of(iso2)` for each `getCountries()` code.
 */
import type { Locale } from "@/lib/i18n/locales";

export const COUNTRY_NAMES: Record<Locale, Readonly<Record<string, string>>> = {
  en: {
    AC: "Ascension Island",
    AD: "Andorra",
    AE: "United Arab Emirates",
    AF: "Afghanistan",
    AG: "Antigua & Barbuda",
    AI: "Anguilla",
    AL: "Albania",
    AM: "Armenia",
    AO: "Angola",
    AR: "Argentina",
    AS: "American Samoa",
    AT: "Austria",
    AU: "Australia",
    AW: "Aruba",
    AX: "Åland Islands",
    AZ: "Azerbaijan",
    BA: "Bosnia & Herzegovina",
    BB: "Barbados",
    BD: "Bangladesh",
    BE: "Belgium",
    BF: "Burkina Faso",
    BG: "Bulgaria",
    BH: "Bahrain",
    BI: "Burundi",
    BJ: "Benin",
    BL: "St. Barthélemy",
    BM: "Bermuda",
    BN: "Brunei",
    BO: "Bolivia",
    BQ: "Caribbean Netherlands",
    BR: "Brazil",
    BS: "Bahamas",
    BT: "Bhutan",
    BW: "Botswana",
    BY: "Belarus",
    BZ: "Belize",
    CA: "Canada",
    CC: "Cocos (Keeling) Islands",
    CD: "Congo - Kinshasa",
    CF: "Central African Republic",
    CG: "Congo - Brazzaville",
    CH: "Switzerland",
    CI: "Côte d’Ivoire",
    CK: "Cook Islands",
    CL: "Chile",
    CM: "Cameroon",
    CN: "China",
    CO: "Colombia",
    CR: "Costa Rica",
    CU: "Cuba",
    CV: "Cape Verde",
    CW: "Curaçao",
    CX: "Christmas Island",
    CY: "Cyprus",
    CZ: "Czechia",
    DE: "Germany",
    DJ: "Djibouti",
    DK: "Denmark",
    DM: "Dominica",
    DO: "Dominican Republic",
    DZ: "Algeria",
    EC: "Ecuador",
    EE: "Estonia",
    EG: "Egypt",
    EH: "Western Sahara",
    ER: "Eritrea",
    ES: "Spain",
    ET: "Ethiopia",
    FI: "Finland",
    FJ: "Fiji",
    FK: "Falkland Islands",
    FM: "Micronesia",
    FO: "Faroe Islands",
    FR: "France",
    GA: "Gabon",
    GB: "United Kingdom",
    GD: "Grenada",
    GE: "Georgia",
    GF: "French Guiana",
    GG: "Guernsey",
    GH: "Ghana",
    GI: "Gibraltar",
    GL: "Greenland",
    GM: "Gambia",
    GN: "Guinea",
    GP: "Guadeloupe",
    GQ: "Equatorial Guinea",
    GR: "Greece",
    GT: "Guatemala",
    GU: "Guam",
    GW: "Guinea-Bissau",
    GY: "Guyana",
    HK: "Hong Kong",
    HN: "Honduras",
    HR: "Croatia",
    HT: "Haiti",
    HU: "Hungary",
    ID: "Indonesia",
    IE: "Ireland",
    IL: "Israel",
    IM: "Isle of Man",
    IN: "India",
    IO: "British Indian Ocean Territory",
    IQ: "Iraq",
    IR: "Iran",
    IS: "Iceland",
    IT: "Italy",
    JE: "Jersey",
    JM: "Jamaica",
    JO: "Jordan",
    JP: "Japan",
    KE: "Kenya",
    KG: "Kyrgyzstan",
    KH: "Cambodia",
    KI: "Kiribati",
    KM: "Comoros",
    KN: "St. Kitts & Nevis",
    KP: "North Korea",
    KR: "South Korea",
    KW: "Kuwait",
    KY: "Cayman Islands",
    KZ: "Kazakhstan",
    LA: "Laos",
    LB: "Lebanon",
    LC: "St. Lucia",
    LI: "Liechtenstein",
    LK: "Sri Lanka",
    LR: "Liberia",
    LS: "Lesotho",
    LT: "Lithuania",
    LU: "Luxembourg",
    LV: "Latvia",
    LY: "Libya",
    MA: "Morocco",
    MC: "Monaco",
    MD: "Moldova",
    ME: "Montenegro",
    MF: "St. Martin",
    MG: "Madagascar",
    MH: "Marshall Islands",
    MK: "North Macedonia",
    ML: "Mali",
    MM: "Myanmar (Burma)",
    MN: "Mongolia",
    MO: "Macao",
    MP: "Northern Mariana Islands",
    MQ: "Martinique",
    MR: "Mauritania",
    MS: "Montserrat",
    MT: "Malta",
    MU: "Mauritius",
    MV: "Maldives",
    MW: "Malawi",
    MX: "Mexico",
    MY: "Malaysia",
    MZ: "Mozambique",
    NA: "Namibia",
    NC: "New Caledonia",
    NE: "Niger",
    NF: "Norfolk Island",
    NG: "Nigeria",
    NI: "Nicaragua",
    NL: "Netherlands",
    NO: "Norway",
    NP: "Nepal",
    NR: "Nauru",
    NU: "Niue",
    NZ: "New Zealand",
    OM: "Oman",
    PA: "Panama",
    PE: "Peru",
    PF: "French Polynesia",
    PG: "Papua New Guinea",
    PH: "Philippines",
    PK: "Pakistan",
    PL: "Poland",
    PM: "St. Pierre & Miquelon",
    PR: "Puerto Rico",
    PS: "Palestine",
    PT: "Portugal",
    PW: "Palau",
    PY: "Paraguay",
    QA: "Qatar",
    RE: "Réunion",
    RO: "Romania",
    RS: "Serbia",
    RU: "Russia",
    RW: "Rwanda",
    SA: "Saudi Arabia",
    SB: "Solomon Islands",
    SC: "Seychelles",
    SD: "Sudan",
    SE: "Sweden",
    SG: "Singapore",
    SH: "St. Helena",
    SI: "Slovenia",
    SJ: "Svalbard & Jan Mayen",
    SK: "Slovakia",
    SL: "Sierra Leone",
    SM: "San Marino",
    SN: "Senegal",
    SO: "Somalia",
    SR: "Suriname",
    SS: "South Sudan",
    ST: "São Tomé & Príncipe",
    SV: "El Salvador",
    SX: "Sint Maarten",
    SY: "Syria",
    SZ: "Eswatini",
    TA: "Tristan da Cunha",
    TC: "Turks & Caicos Islands",
    TD: "Chad",
    TG: "Togo",
    TH: "Thailand",
    TJ: "Tajikistan",
    TK: "Tokelau",
    TL: "Timor-Leste",
    TM: "Turkmenistan",
    TN: "Tunisia",
    TO: "Tonga",
    TR: "Türkiye",
    TT: "Trinidad & Tobago",
    TV: "Tuvalu",
    TW: "Taiwan",
    TZ: "Tanzania",
    UA: "Ukraine",
    UG: "Uganda",
    US: "United States",
    UY: "Uruguay",
    UZ: "Uzbekistan",
    VA: "Vatican City",
    VC: "St. Vincent & Grenadines",
    VE: "Venezuela",
    VG: "British Virgin Islands",
    VI: "U.S. Virgin Islands",
    VN: "Vietnam",
    VU: "Vanuatu",
    WF: "Wallis & Futuna",
    WS: "Samoa",
    XK: "Kosovo",
    YE: "Yemen",
    YT: "Mayotte",
    ZA: "South Africa",
    ZM: "Zambia",
    ZW: "Zimbabwe",
  },
  ar: {
    AC: "جزيرة أسينشيون",
    AD: "أندورا",
    AE: "الإمارات العربية المتحدة",
    AF: "أفغانستان",
    AG: "أنتيغوا وبربودا",
    AI: "أنغويلا",
    AL: "ألبانيا",
    AM: "أرمينيا",
    AO: "أنغولا",
    AR: "الأرجنتين",
    AS: "ساموا الأمريكية",
    AT: "النمسا",
    AU: "أستراليا",
    AW: "أروبا",
    AX: "جزر آلاند",
    AZ: "أذربيجان",
    BA: "البوسنة والهرسك",
    BB: "بربادوس",
    BD: "بنغلاديش",
    BE: "بلجيكا",
    BF: "بوركينا فاسو",
    BG: "بلغاريا",
    BH: "البحرين",
    BI: "بوروندي",
    BJ: "بنين",
    BL: "سان بارتليمي",
    BM: "برمودا",
    BN: "بروناي",
    BO: "بوليفيا",
    BQ: "هولندا الكاريبية",
    BR: "البرازيل",
    BS: "جزر البهاما",
    BT: "بوتان",
    BW: "بوتسوانا",
    BY: "بيلاروس",
    BZ: "بليز",
    CA: "كندا",
    CC: "جزر كوكوس (كيلينغ)",
    CD: "الكونغو - كينشاسا",
    CF: "جمهورية أفريقيا الوسطى",
    CG: "الكونغو - برازافيل",
    CH: "سويسرا",
    CI: "ساحل العاج",
    CK: "جزر كوك",
    CL: "تشيلي",
    CM: "الكاميرون",
    CN: "الصين",
    CO: "كولومبيا",
    CR: "كوستاريكا",
    CU: "كوبا",
    CV: "الرأس الأخضر",
    CW: "كوراساو",
    CX: "جزيرة كريسماس",
    CY: "قبرص",
    CZ: "التشيك",
    DE: "ألمانيا",
    DJ: "جيبوتي",
    DK: "الدانمرك",
    DM: "دومينيكا",
    DO: "جمهورية الدومينيكان",
    DZ: "الجزائر",
    EC: "الإكوادور",
    EE: "إستونيا",
    EG: "مصر",
    EH: "الصحراء الغربية",
    ER: "إريتريا",
    ES: "إسبانيا",
    ET: "إثيوبيا",
    FI: "فنلندا",
    FJ: "فيجي",
    FK: "جزر فوكلاند",
    FM: "ميكرونيزيا",
    FO: "جزر فارو",
    FR: "فرنسا",
    GA: "الغابون",
    GB: "المملكة المتحدة",
    GD: "غرينادا",
    GE: "جورجيا",
    GF: "غويانا الفرنسية",
    GG: "غيرنزي",
    GH: "غانا",
    GI: "جبل طارق",
    GL: "غرينلاند",
    GM: "غامبيا",
    GN: "غينيا",
    GP: "غوادلوب",
    GQ: "غينيا الاستوائية",
    GR: "اليونان",
    GT: "غواتيمالا",
    GU: "غوام",
    GW: "غينيا بيساو",
    GY: "غيانا",
    HK: "هونغ كونغ",
    HN: "هندوراس",
    HR: "كرواتيا",
    HT: "هايتي",
    HU: "هنغاريا",
    ID: "إندونيسيا",
    IE: "أيرلندا",
    IL: "إسرائيل",
    IM: "جزيرة مان",
    IN: "الهند",
    IO: "الإقليم البريطاني في المحيط الهندي",
    IQ: "العراق",
    IR: "إيران",
    IS: "آيسلندا",
    IT: "إيطاليا",
    JE: "جيرسي",
    JM: "جامايكا",
    JO: "الأردن",
    JP: "اليابان",
    KE: "كينيا",
    KG: "قيرغيزستان",
    KH: "كمبوديا",
    KI: "كيريباتي",
    KM: "جزر القمر",
    KN: "سانت كيتس ونيفيس",
    KP: "كوريا الشمالية",
    KR: "كوريا الجنوبية",
    KW: "الكويت",
    KY: "جزر كايمان",
    KZ: "كازاخستان",
    LA: "لاوس",
    LB: "لبنان",
    LC: "سانت لوسيا",
    LI: "ليختنشتاين",
    LK: "سريلانكا",
    LR: "ليبيريا",
    LS: "ليسوتو",
    LT: "ليتوانيا",
    LU: "لوكسمبورغ",
    LV: "لاتفيا",
    LY: "ليبيا",
    MA: "المغرب",
    MC: "موناكو",
    MD: "مولدوفا",
    ME: "الجبل الأسود",
    MF: "سان مارتن",
    MG: "مدغشقر",
    MH: "جزر مارشال",
    MK: "مقدونيا الشمالية",
    ML: "مالي",
    MM: "ميانمار (بورما)",
    MN: "منغوليا",
    MO: "ماكاو",
    MP: "جزر ماريانا الشمالية",
    MQ: "جزر المارتينيك",
    MR: "موريتانيا",
    MS: "مونتسرات",
    MT: "مالطا",
    MU: "موريشيوس",
    MV: "جزر المالديف",
    MW: "ملاوي",
    MX: "المكسيك",
    MY: "ماليزيا",
    MZ: "موزمبيق",
    NA: "ناميبيا",
    NC: "كاليدونيا الجديدة",
    NE: "النيجر",
    NF: "جزيرة نورفولك",
    NG: "نيجيريا",
    NI: "نيكاراغوا",
    NL: "هولندا",
    NO: "النرويج",
    NP: "نيبال",
    NR: "ناورو",
    NU: "نيوي",
    NZ: "نيوزيلندا",
    OM: "عُمان",
    PA: "بنما",
    PE: "بيرو",
    PF: "بولينيزيا الفرنسية",
    PG: "بابوا غينيا الجديدة",
    PH: "الفلبين",
    PK: "باكستان",
    PL: "بولندا",
    PM: "سان بيير ومكويلون",
    PR: "بورتوريكو",
    PS: "فلسطين",
    PT: "البرتغال",
    PW: "بالاو",
    PY: "باراغواي",
    QA: "قطر",
    RE: "روينيون",
    RO: "رومانيا",
    RS: "صربيا",
    RU: "روسيا",
    RW: "رواندا",
    SA: "المملكة العربية السعودية",
    SB: "جزر سليمان",
    SC: "سيشل",
    SD: "السودان",
    SE: "السويد",
    SG: "سنغافورة",
    SH: "سانت هيلينا",
    SI: "سلوفينيا",
    SJ: "سفالبارد وجان ماين",
    SK: "سلوفاكيا",
    SL: "سيراليون",
    SM: "سان مارينو",
    SN: "السنغال",
    SO: "الصومال",
    SR: "سورينام",
    SS: "جنوب السودان",
    ST: "ساو تومي وبرينسيبي",
    SV: "السلفادور",
    SX: "سانت مارتن",
    SY: "سوريا",
    SZ: "إسواتيني",
    TA: "تريستان دا كونا",
    TC: "جزر توركس وكايكوس",
    TD: "تشاد",
    TG: "توغو",
    TH: "تايلاند",
    TJ: "طاجيكستان",
    TK: "توكيلاو",
    TL: "تيمور - ليشتي",
    TM: "تركمانستان",
    TN: "تونس",
    TO: "تونغا",
    TR: "تركيا",
    TT: "ترينيداد وتوباغو",
    TV: "توفالو",
    TW: "تايوان",
    TZ: "تنزانيا",
    UA: "أوكرانيا",
    UG: "أوغندا",
    US: "الولايات المتحدة",
    UY: "أورغواي",
    UZ: "أوزبكستان",
    VA: "الفاتيكان",
    VC: "سانت فنسنت وجزر غرينادين",
    VE: "فنزويلا",
    VG: "جزر فيرجن البريطانية",
    VI: "جزر فيرجن الأمريكية",
    VN: "فيتنام",
    VU: "فانواتو",
    WF: "جزر والس وفوتونا",
    WS: "ساموا",
    XK: "كوسوفو",
    YE: "اليمن",
    YT: "مايوت",
    ZA: "جنوب أفريقيا",
    ZM: "زامبيا",
    ZW: "زيمبابوي",
  },
};

/** The country's name in the given locale, or its ISO code when none is known. Pure and deterministic. */
export function countryName(locale: Locale, iso2: string): string {
  return COUNTRY_NAMES[locale]?.[iso2] ?? iso2;
}
