-- ===========================================================================
-- Installer Jobs — the PLACE CATALOGUE (Egypt governorates and cities)
--
-- One reference catalogue of places, generated from
-- `frontend/src/lib/installer/location-data.ts` (a unit test fails if the two ever
-- diverge), so there is one catalogue with two readers rather than two lists.
-- Every later migration that needs "where is this?" asks it HERE: the canonical
-- job location (jobs.governorate_key / city_key), the caller's service areas, the
-- board's governorate / city filters and the Overall Match location component.
--
-- LOCATION IS RESOLVED EXACTLY, NEVER GUESSED. A free-text place resolves to a
-- catalogue place only when its text, after lossless orthographic normalisation
-- (case, whitespace, Arabic diacritics and tatweel), equals one of that place's
-- own catalogue names — exactly what `frontend/src/lib/installer/
-- opportunity-location.ts` does.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Place resolution (immutable, catalogue-backed)
-- ---------------------------------------------------------------------------
create function app.normalize_place(p_text text)
returns text
language sql
immutable
set search_path = ''
as $$
  -- NFKC, drop Arabic tashkeel (U+064B-U+065F, U+0670) and tatweel (U+0640),
  -- collapse whitespace, trim, lower-case. Mirrors normalizePlace() in the app.
  select lower(btrim(regexp_replace(
           regexp_replace(normalize(coalesce(p_text, ''), nfkc), E'[\u064B-\u065F\u0670\u0640]', '', 'g'),
           E'\\s+', ' ', 'g')));
$$;

comment on function app.normalize_place(text) is
  'Lossless orthographic normalisation of a place name (case, whitespace, Arabic diacritics, tatweel). Mirrors normalizePlace() in frontend/src/lib/installer/opportunity-location.ts.';

-- The catalogue is DATA: two small reference tables generated from
-- `frontend/src/lib/installer/location-data.ts` (a unit test fails if they ever
-- diverge). A name is stored once as written and once normalised (a generated
-- column), so resolving a place is an index probe — not a scan that re-normalises
-- ~400 names per call, which matters when a board of thousands of jobs is
-- resolved row by row.
create table app.place_governorates (
  key       text not null,
  name      text not null,
  name_norm text generated always as (app.normalize_place(name)) stored,
  primary key (key, name)
);
create index ix_place_governorates_norm on app.place_governorates (name_norm);

create table app.place_cities (
  governorate_key text not null,
  key             text not null,
  name            text not null,
  name_norm       text generated always as (app.normalize_place(name)) stored,
  primary key (governorate_key, key, name)
);
create index ix_place_cities_norm on app.place_cities (governorate_key, name_norm);

comment on table app.place_governorates is
  'Egypt governorate catalogue: every key + Arabic + English name. Reference data generated from frontend/src/lib/installer/location-data.ts (parity-tested). Read-only to clients.';
comment on table app.place_cities is
  'Egypt city catalogue, inside its governorate: every key + Arabic + English name. "other" is a catalogue entry like any other. Generated from frontend/src/lib/installer/location-data.ts (parity-tested). Read-only to clients.';

insert into app.place_governorates (key, name) values
    ('cairo', 'cairo'),
    ('cairo', 'القاهرة'),
    ('cairo', 'Cairo'),
    ('giza', 'giza'),
    ('giza', 'الجيزة'),
    ('giza', 'Giza'),
    ('alexandria', 'alexandria'),
    ('alexandria', 'الإسكندرية'),
    ('alexandria', 'Alexandria'),
    ('dakahlia', 'dakahlia'),
    ('dakahlia', 'الدقهلية'),
    ('dakahlia', 'Dakahlia'),
    ('red-sea', 'red-sea'),
    ('red-sea', 'البحر الأحمر'),
    ('red-sea', 'Red Sea'),
    ('beheira', 'beheira'),
    ('beheira', 'البحيرة'),
    ('beheira', 'Beheira'),
    ('fayoum', 'fayoum'),
    ('fayoum', 'الفيوم'),
    ('fayoum', 'Fayoum'),
    ('gharbia', 'gharbia'),
    ('gharbia', 'الغربية'),
    ('gharbia', 'Gharbia'),
    ('ismailia', 'ismailia'),
    ('ismailia', 'الإسماعيلية'),
    ('ismailia', 'Ismailia'),
    ('monufia', 'monufia'),
    ('monufia', 'المنوفية'),
    ('monufia', 'Monufia'),
    ('minya', 'minya'),
    ('minya', 'المنيا'),
    ('minya', 'Minya'),
    ('qalyubia', 'qalyubia'),
    ('qalyubia', 'القليوبية'),
    ('qalyubia', 'Qalyubia'),
    ('new-valley', 'new-valley'),
    ('new-valley', 'الوادي الجديد'),
    ('new-valley', 'New Valley'),
    ('suez', 'suez'),
    ('suez', 'السويس'),
    ('suez', 'Suez'),
    ('aswan', 'aswan'),
    ('aswan', 'أسوان'),
    ('aswan', 'Aswan'),
    ('assiut', 'assiut'),
    ('assiut', 'أسيوط'),
    ('assiut', 'Assiut'),
    ('beni-suef', 'beni-suef'),
    ('beni-suef', 'بني سويف'),
    ('beni-suef', 'Beni Suef'),
    ('port-said', 'port-said'),
    ('port-said', 'بورسعيد'),
    ('port-said', 'Port Said'),
    ('damietta', 'damietta'),
    ('damietta', 'دمياط'),
    ('damietta', 'Damietta'),
    ('sharqia', 'sharqia'),
    ('sharqia', 'الشرقية'),
    ('sharqia', 'Sharqia'),
    ('south-sinai', 'south-sinai'),
    ('south-sinai', 'جنوب سيناء'),
    ('south-sinai', 'South Sinai'),
    ('kafr-el-sheikh', 'kafr-el-sheikh'),
    ('kafr-el-sheikh', 'كفر الشيخ'),
    ('kafr-el-sheikh', 'Kafr El Sheikh'),
    ('matrouh', 'matrouh'),
    ('matrouh', 'مطروح'),
    ('matrouh', 'Matrouh'),
    ('luxor', 'luxor'),
    ('luxor', 'الأقصر'),
    ('luxor', 'Luxor'),
    ('qena', 'qena'),
    ('qena', 'قنا'),
    ('qena', 'Qena'),
    ('north-sinai', 'north-sinai'),
    ('north-sinai', 'شمال سيناء'),
    ('north-sinai', 'North Sinai'),
    ('sohag', 'sohag'),
    ('sohag', 'سوهاج'),
    ('sohag', 'Sohag');

insert into app.place_cities (governorate_key, key, name) values
    ('cairo', 'new-cairo', 'new-cairo'),
    ('cairo', 'new-cairo', 'القاهرة الجديدة'),
    ('cairo', 'new-cairo', 'New Cairo'),
    ('cairo', 'nasr-city', 'nasr-city'),
    ('cairo', 'nasr-city', 'مدينة نصر'),
    ('cairo', 'nasr-city', 'Nasr City'),
    ('cairo', 'heliopolis', 'heliopolis'),
    ('cairo', 'heliopolis', 'مصر الجديدة'),
    ('cairo', 'heliopolis', 'Heliopolis'),
    ('cairo', 'maadi', 'maadi'),
    ('cairo', 'maadi', 'المعادي'),
    ('cairo', 'maadi', 'Maadi'),
    ('cairo', 'downtown', 'downtown'),
    ('cairo', 'downtown', 'وسط البلد'),
    ('cairo', 'downtown', 'Downtown Cairo'),
    ('cairo', 'shorouk', 'shorouk'),
    ('cairo', 'shorouk', 'الشروق'),
    ('cairo', 'shorouk', 'El Shorouk'),
    ('cairo', 'badr', 'badr'),
    ('cairo', 'badr', 'بدر'),
    ('cairo', 'badr', 'Badr'),
    ('cairo', 'other', 'other'),
    ('cairo', 'other', 'مدينة أخرى'),
    ('cairo', 'other', 'Other city'),
    ('giza', 'giza-city', 'giza-city'),
    ('giza', 'giza-city', 'مدينة الجيزة'),
    ('giza', 'giza-city', 'Giza City'),
    ('giza', 'sheikh-zayed', 'sheikh-zayed'),
    ('giza', 'sheikh-zayed', 'الشيخ زايد'),
    ('giza', 'sheikh-zayed', 'Sheikh Zayed'),
    ('giza', 'october-6', 'october-6'),
    ('giza', 'october-6', 'السادس من أكتوبر'),
    ('giza', 'october-6', '6th of October'),
    ('giza', 'dokki', 'dokki'),
    ('giza', 'dokki', 'الدقي'),
    ('giza', 'dokki', 'Dokki'),
    ('giza', 'mohandessin', 'mohandessin'),
    ('giza', 'mohandessin', 'المهندسين'),
    ('giza', 'mohandessin', 'Mohandessin'),
    ('giza', 'haram', 'haram'),
    ('giza', 'haram', 'الهرم'),
    ('giza', 'haram', 'Haram'),
    ('giza', 'other', 'other'),
    ('giza', 'other', 'مدينة أخرى'),
    ('giza', 'other', 'Other city'),
    ('alexandria', 'alexandria-city', 'alexandria-city'),
    ('alexandria', 'alexandria-city', 'الإسكندرية'),
    ('alexandria', 'alexandria-city', 'Alexandria City'),
    ('alexandria', 'borg-el-arab', 'borg-el-arab'),
    ('alexandria', 'borg-el-arab', 'برج العرب'),
    ('alexandria', 'borg-el-arab', 'Borg El Arab'),
    ('alexandria', 'amreya', 'amreya'),
    ('alexandria', 'amreya', 'العامرية'),
    ('alexandria', 'amreya', 'Amreya'),
    ('alexandria', 'other', 'other'),
    ('alexandria', 'other', 'مدينة أخرى'),
    ('alexandria', 'other', 'Other city'),
    ('dakahlia', 'mansoura', 'mansoura'),
    ('dakahlia', 'mansoura', 'المنصورة'),
    ('dakahlia', 'mansoura', 'Mansoura'),
    ('dakahlia', 'mit-ghamr', 'mit-ghamr'),
    ('dakahlia', 'mit-ghamr', 'ميت غمر'),
    ('dakahlia', 'mit-ghamr', 'Mit Ghamr'),
    ('dakahlia', 'belqas', 'belqas'),
    ('dakahlia', 'belqas', 'بلقاس'),
    ('dakahlia', 'belqas', 'Belqas'),
    ('dakahlia', 'other', 'other'),
    ('dakahlia', 'other', 'مدينة أخرى'),
    ('dakahlia', 'other', 'Other city'),
    ('red-sea', 'hurghada', 'hurghada'),
    ('red-sea', 'hurghada', 'الغردقة'),
    ('red-sea', 'hurghada', 'Hurghada'),
    ('red-sea', 'safaga', 'safaga'),
    ('red-sea', 'safaga', 'سفاجا'),
    ('red-sea', 'safaga', 'Safaga'),
    ('red-sea', 'marsa-alam', 'marsa-alam'),
    ('red-sea', 'marsa-alam', 'مرسى علم'),
    ('red-sea', 'marsa-alam', 'Marsa Alam'),
    ('red-sea', 'other', 'other'),
    ('red-sea', 'other', 'مدينة أخرى'),
    ('red-sea', 'other', 'Other city'),
    ('beheira', 'damanhur', 'damanhur'),
    ('beheira', 'damanhur', 'دمنهور'),
    ('beheira', 'damanhur', 'Damanhur'),
    ('beheira', 'kafr-el-dawwar', 'kafr-el-dawwar'),
    ('beheira', 'kafr-el-dawwar', 'كفر الدوار'),
    ('beheira', 'kafr-el-dawwar', 'Kafr El Dawwar'),
    ('beheira', 'rashid', 'rashid'),
    ('beheira', 'rashid', 'رشيد'),
    ('beheira', 'rashid', 'Rosetta'),
    ('beheira', 'other', 'other'),
    ('beheira', 'other', 'مدينة أخرى'),
    ('beheira', 'other', 'Other city'),
    ('fayoum', 'fayoum-city', 'fayoum-city'),
    ('fayoum', 'fayoum-city', 'الفيوم'),
    ('fayoum', 'fayoum-city', 'Fayoum City'),
    ('fayoum', 'sinnuris', 'sinnuris'),
    ('fayoum', 'sinnuris', 'سنورس'),
    ('fayoum', 'sinnuris', 'Sinnuris'),
    ('fayoum', 'ibshaway', 'ibshaway'),
    ('fayoum', 'ibshaway', 'إبشواي'),
    ('fayoum', 'ibshaway', 'Ibshaway'),
    ('fayoum', 'other', 'other'),
    ('fayoum', 'other', 'مدينة أخرى'),
    ('fayoum', 'other', 'Other city'),
    ('gharbia', 'tanta', 'tanta'),
    ('gharbia', 'tanta', 'طنطا'),
    ('gharbia', 'tanta', 'Tanta'),
    ('gharbia', 'mahalla', 'mahalla'),
    ('gharbia', 'mahalla', 'المحلة الكبرى'),
    ('gharbia', 'mahalla', 'El Mahalla El Kubra'),
    ('gharbia', 'kafr-el-zayat', 'kafr-el-zayat'),
    ('gharbia', 'kafr-el-zayat', 'كفر الزيات'),
    ('gharbia', 'kafr-el-zayat', 'Kafr El Zayat'),
    ('gharbia', 'other', 'other'),
    ('gharbia', 'other', 'مدينة أخرى'),
    ('gharbia', 'other', 'Other city'),
    ('ismailia', 'ismailia-city', 'ismailia-city'),
    ('ismailia', 'ismailia-city', 'الإسماعيلية'),
    ('ismailia', 'ismailia-city', 'Ismailia City'),
    ('ismailia', 'fayed', 'fayed'),
    ('ismailia', 'fayed', 'فايد'),
    ('ismailia', 'fayed', 'Fayed'),
    ('ismailia', 'el-qantara', 'el-qantara'),
    ('ismailia', 'el-qantara', 'القنطرة'),
    ('ismailia', 'el-qantara', 'El Qantara'),
    ('ismailia', 'other', 'other'),
    ('ismailia', 'other', 'مدينة أخرى'),
    ('ismailia', 'other', 'Other city'),
    ('monufia', 'shebin-el-kom', 'shebin-el-kom'),
    ('monufia', 'shebin-el-kom', 'شبين الكوم'),
    ('monufia', 'shebin-el-kom', 'Shebin El Kom'),
    ('monufia', 'sadat-city', 'sadat-city'),
    ('monufia', 'sadat-city', 'مدينة السادات'),
    ('monufia', 'sadat-city', 'Sadat City'),
    ('monufia', 'menouf', 'menouf'),
    ('monufia', 'menouf', 'منوف'),
    ('monufia', 'menouf', 'Menouf'),
    ('monufia', 'other', 'other'),
    ('monufia', 'other', 'مدينة أخرى'),
    ('monufia', 'other', 'Other city'),
    ('minya', 'minya-city', 'minya-city'),
    ('minya', 'minya-city', 'المنيا'),
    ('minya', 'minya-city', 'Minya City'),
    ('minya', 'mallawi', 'mallawi'),
    ('minya', 'mallawi', 'ملوي'),
    ('minya', 'mallawi', 'Mallawi'),
    ('minya', 'samalut', 'samalut'),
    ('minya', 'samalut', 'سمالوط'),
    ('minya', 'samalut', 'Samalut'),
    ('minya', 'other', 'other'),
    ('minya', 'other', 'مدينة أخرى'),
    ('minya', 'other', 'Other city'),
    ('qalyubia', 'banha', 'banha'),
    ('qalyubia', 'banha', 'بنها'),
    ('qalyubia', 'banha', 'Banha'),
    ('qalyubia', 'shubra-el-kheima', 'shubra-el-kheima'),
    ('qalyubia', 'shubra-el-kheima', 'شبرا الخيمة'),
    ('qalyubia', 'shubra-el-kheima', 'Shubra El Kheima'),
    ('qalyubia', 'obour', 'obour'),
    ('qalyubia', 'obour', 'العبور'),
    ('qalyubia', 'obour', 'Obour'),
    ('qalyubia', 'other', 'other'),
    ('qalyubia', 'other', 'مدينة أخرى'),
    ('qalyubia', 'other', 'Other city'),
    ('new-valley', 'kharga', 'kharga'),
    ('new-valley', 'kharga', 'الخارجة'),
    ('new-valley', 'kharga', 'Kharga'),
    ('new-valley', 'dakhla', 'dakhla'),
    ('new-valley', 'dakhla', 'الداخلة'),
    ('new-valley', 'dakhla', 'Dakhla'),
    ('new-valley', 'farafra', 'farafra'),
    ('new-valley', 'farafra', 'الفرافرة'),
    ('new-valley', 'farafra', 'Farafra'),
    ('new-valley', 'other', 'other'),
    ('new-valley', 'other', 'مدينة أخرى'),
    ('new-valley', 'other', 'Other city'),
    ('suez', 'suez-city', 'suez-city'),
    ('suez', 'suez-city', 'السويس'),
    ('suez', 'suez-city', 'Suez City'),
    ('suez', 'ain-sokhna', 'ain-sokhna'),
    ('suez', 'ain-sokhna', 'العين السخنة'),
    ('suez', 'ain-sokhna', 'Ain Sokhna'),
    ('suez', 'other', 'other'),
    ('suez', 'other', 'مدينة أخرى'),
    ('suez', 'other', 'Other city'),
    ('aswan', 'aswan-city', 'aswan-city'),
    ('aswan', 'aswan-city', 'أسوان'),
    ('aswan', 'aswan-city', 'Aswan City'),
    ('aswan', 'kom-ombo', 'kom-ombo'),
    ('aswan', 'kom-ombo', 'كوم أمبو'),
    ('aswan', 'kom-ombo', 'Kom Ombo'),
    ('aswan', 'edfu', 'edfu'),
    ('aswan', 'edfu', 'إدفو'),
    ('aswan', 'edfu', 'Edfu'),
    ('aswan', 'other', 'other'),
    ('aswan', 'other', 'مدينة أخرى'),
    ('aswan', 'other', 'Other city'),
    ('assiut', 'assiut-city', 'assiut-city'),
    ('assiut', 'assiut-city', 'أسيوط'),
    ('assiut', 'assiut-city', 'Assiut City'),
    ('assiut', 'dairut', 'dairut'),
    ('assiut', 'dairut', 'ديروط'),
    ('assiut', 'dairut', 'Dairut'),
    ('assiut', 'manfalut', 'manfalut'),
    ('assiut', 'manfalut', 'منفلوط'),
    ('assiut', 'manfalut', 'Manfalut'),
    ('assiut', 'other', 'other'),
    ('assiut', 'other', 'مدينة أخرى'),
    ('assiut', 'other', 'Other city'),
    ('beni-suef', 'beni-suef-city', 'beni-suef-city'),
    ('beni-suef', 'beni-suef-city', 'بني سويف'),
    ('beni-suef', 'beni-suef-city', 'Beni Suef City'),
    ('beni-suef', 'wasta', 'wasta'),
    ('beni-suef', 'wasta', 'الواسطى'),
    ('beni-suef', 'wasta', 'El Wasta'),
    ('beni-suef', 'biba', 'biba'),
    ('beni-suef', 'biba', 'ببا'),
    ('beni-suef', 'biba', 'Biba'),
    ('beni-suef', 'other', 'other'),
    ('beni-suef', 'other', 'مدينة أخرى'),
    ('beni-suef', 'other', 'Other city'),
    ('port-said', 'port-said-city', 'port-said-city'),
    ('port-said', 'port-said-city', 'بورسعيد'),
    ('port-said', 'port-said-city', 'Port Said City'),
    ('port-said', 'port-fouad', 'port-fouad'),
    ('port-said', 'port-fouad', 'بورفؤاد'),
    ('port-said', 'port-fouad', 'Port Fouad'),
    ('port-said', 'other', 'other'),
    ('port-said', 'other', 'مدينة أخرى'),
    ('port-said', 'other', 'Other city'),
    ('damietta', 'damietta-city', 'damietta-city'),
    ('damietta', 'damietta-city', 'دمياط'),
    ('damietta', 'damietta-city', 'Damietta City'),
    ('damietta', 'new-damietta', 'new-damietta'),
    ('damietta', 'new-damietta', 'دمياط الجديدة'),
    ('damietta', 'new-damietta', 'New Damietta'),
    ('damietta', 'ras-el-bar', 'ras-el-bar'),
    ('damietta', 'ras-el-bar', 'رأس البر'),
    ('damietta', 'ras-el-bar', 'Ras El Bar'),
    ('damietta', 'other', 'other'),
    ('damietta', 'other', 'مدينة أخرى'),
    ('damietta', 'other', 'Other city'),
    ('sharqia', 'zagazig', 'zagazig'),
    ('sharqia', 'zagazig', 'الزقازيق'),
    ('sharqia', 'zagazig', 'Zagazig'),
    ('sharqia', 'tenth-ramadan', 'tenth-ramadan'),
    ('sharqia', 'tenth-ramadan', 'العاشر من رمضان'),
    ('sharqia', 'tenth-ramadan', '10th of Ramadan'),
    ('sharqia', 'belbeis', 'belbeis'),
    ('sharqia', 'belbeis', 'بلبيس'),
    ('sharqia', 'belbeis', 'Belbeis'),
    ('sharqia', 'other', 'other'),
    ('sharqia', 'other', 'مدينة أخرى'),
    ('sharqia', 'other', 'Other city'),
    ('south-sinai', 'sharm-el-sheikh', 'sharm-el-sheikh'),
    ('south-sinai', 'sharm-el-sheikh', 'شرم الشيخ'),
    ('south-sinai', 'sharm-el-sheikh', 'Sharm El Sheikh'),
    ('south-sinai', 'dahab', 'dahab'),
    ('south-sinai', 'dahab', 'دهب'),
    ('south-sinai', 'dahab', 'Dahab'),
    ('south-sinai', 'el-tor', 'el-tor'),
    ('south-sinai', 'el-tor', 'الطور'),
    ('south-sinai', 'el-tor', 'El Tor'),
    ('south-sinai', 'other', 'other'),
    ('south-sinai', 'other', 'مدينة أخرى'),
    ('south-sinai', 'other', 'Other city'),
    ('kafr-el-sheikh', 'kafr-el-sheikh-city', 'kafr-el-sheikh-city'),
    ('kafr-el-sheikh', 'kafr-el-sheikh-city', 'كفر الشيخ'),
    ('kafr-el-sheikh', 'kafr-el-sheikh-city', 'Kafr El Sheikh City'),
    ('kafr-el-sheikh', 'desouk', 'desouk'),
    ('kafr-el-sheikh', 'desouk', 'دسوق'),
    ('kafr-el-sheikh', 'desouk', 'Desouk'),
    ('kafr-el-sheikh', 'baltim', 'baltim'),
    ('kafr-el-sheikh', 'baltim', 'بلطيم'),
    ('kafr-el-sheikh', 'baltim', 'Baltim'),
    ('kafr-el-sheikh', 'other', 'other'),
    ('kafr-el-sheikh', 'other', 'مدينة أخرى'),
    ('kafr-el-sheikh', 'other', 'Other city'),
    ('matrouh', 'marsa-matrouh', 'marsa-matrouh'),
    ('matrouh', 'marsa-matrouh', 'مرسى مطروح'),
    ('matrouh', 'marsa-matrouh', 'Marsa Matrouh'),
    ('matrouh', 'el-alamein', 'el-alamein'),
    ('matrouh', 'el-alamein', 'العلمين'),
    ('matrouh', 'el-alamein', 'El Alamein'),
    ('matrouh', 'siwa', 'siwa'),
    ('matrouh', 'siwa', 'سيوة'),
    ('matrouh', 'siwa', 'Siwa'),
    ('matrouh', 'other', 'other'),
    ('matrouh', 'other', 'مدينة أخرى'),
    ('matrouh', 'other', 'Other city'),
    ('luxor', 'luxor-city', 'luxor-city'),
    ('luxor', 'luxor-city', 'الأقصر'),
    ('luxor', 'luxor-city', 'Luxor City'),
    ('luxor', 'esna', 'esna'),
    ('luxor', 'esna', 'إسنا'),
    ('luxor', 'esna', 'Esna'),
    ('luxor', 'armant', 'armant'),
    ('luxor', 'armant', 'أرمنت'),
    ('luxor', 'armant', 'Armant'),
    ('luxor', 'other', 'other'),
    ('luxor', 'other', 'مدينة أخرى'),
    ('luxor', 'other', 'Other city'),
    ('qena', 'qena-city', 'qena-city'),
    ('qena', 'qena-city', 'قنا'),
    ('qena', 'qena-city', 'Qena City'),
    ('qena', 'nag-hammadi', 'nag-hammadi'),
    ('qena', 'nag-hammadi', 'نجع حمادي'),
    ('qena', 'nag-hammadi', 'Nag Hammadi'),
    ('qena', 'qift', 'qift'),
    ('qena', 'qift', 'قفط'),
    ('qena', 'qift', 'Qift'),
    ('qena', 'other', 'other'),
    ('qena', 'other', 'مدينة أخرى'),
    ('qena', 'other', 'Other city'),
    ('north-sinai', 'arish', 'arish'),
    ('north-sinai', 'arish', 'العريش'),
    ('north-sinai', 'arish', 'Arish'),
    ('north-sinai', 'bir-el-abd', 'bir-el-abd'),
    ('north-sinai', 'bir-el-abd', 'بئر العبد'),
    ('north-sinai', 'bir-el-abd', 'Bir El Abd'),
    ('north-sinai', 'sheikh-zuwied', 'sheikh-zuwied'),
    ('north-sinai', 'sheikh-zuwied', 'الشيخ زويد'),
    ('north-sinai', 'sheikh-zuwied', 'Sheikh Zuweid'),
    ('north-sinai', 'other', 'other'),
    ('north-sinai', 'other', 'مدينة أخرى'),
    ('north-sinai', 'other', 'Other city'),
    ('sohag', 'sohag-city', 'sohag-city'),
    ('sohag', 'sohag-city', 'سوهاج'),
    ('sohag', 'sohag-city', 'Sohag City'),
    ('sohag', 'akhmim', 'akhmim'),
    ('sohag', 'akhmim', 'أخميم'),
    ('sohag', 'akhmim', 'Akhmim'),
    ('sohag', 'girga', 'girga'),
    ('sohag', 'girga', 'جرجا'),
    ('sohag', 'girga', 'Girga'),
    ('sohag', 'other', 'other'),
    ('sohag', 'other', 'مدينة أخرى'),
    ('sohag', 'other', 'Other city');

-- Reference data about places, not about people: readable, never writable.
revoke all on app.place_governorates, app.place_cities from public, anon, authenticated, service_role;
grant select on app.place_governorates, app.place_cities to authenticated, service_role;

-- No SET search_path on purpose: every name below is schema-qualified, and a function
-- SET clause costs a GUC save/restore on EVERY call, which dominates when a board of
-- thousands of jobs is resolved row by row.
create function app.resolve_governorate(p_text text)
returns text
language sql
stable
as $$
  select g.key
  from app.place_governorates g
  where g.name_norm = (select nullif(app.normalize_place(p_text), ''))
  limit 1;
$$;

comment on function app.resolve_governorate(text) is
  'The catalogue governorate key whose key, Arabic or English name equals p_text after normalisation, or NULL. Backed by app.place_governorates (generated from frontend/src/lib/installer/location-data.ts, parity-tested).';

create function app.resolve_city(p_governorate_key text, p_text text)
returns text
language sql
stable
as $$
  select c.key
  from app.place_cities c
  where c.governorate_key = p_governorate_key
    and c.name_norm = (select nullif(app.normalize_place(p_text), ''))
  limit 1;
$$;

comment on function app.resolve_city(text, text) is
  'The catalogue city key INSIDE the given governorate that p_text names exactly, or NULL. "other" is a catalogue entry like any other. Backed by app.place_cities (generated from frontend/src/lib/installer/location-data.ts, parity-tested).';
