export const settingsCopy = {
  ar: {
    title: "الإعدادات", subtitle: "إدارة حسابك وبياناتك الشخصية والإشعارات والخصوصية والأمان.",
    preview: "معاينة فقط — التغييرات هنا لا تؤثر على حسابك الحقيقي.",
    personal: "البيانات الشخصية", personalHint: "قم بإدارة بياناتك الشخصية ومعلومات التواصل الخاصة بحسابك.",
    name: "الاسم المعروض", username: "اسم المستخدم", usernameHint: "سيظهر اسم المستخدم في رابط ملفك الشخصي.",
    email: "البريد الإلكتروني", optional: "اختياري", phone: "رقم الهاتف", secondaryPhone: "رقم هاتف إضافي",
    addPhone: "إضافة هاتف آخر", removePhone: "إزالة الهاتف الإضافي", save: "حفظ التغييرات",
    saved: "تم حفظ التغييرات في هذه المعاينة فقط. لم يتغير حسابك الحقيقي.", phoneError: "أدخل رقم هاتف صحيحًا مع اختيار الدولة.",
    security: "الخصوصية والأمان", securityHint: "حافظ على أمان حسابك وبياناتك الشخصية.",
    login: "طرق تسجيل الدخول", loginHint: "حالات توضيحية فقط؛ لا يتم ربط أي حساب من هذه المعاينة.",
    connected: "متصل", disconnected: "غير متصل",
    sessions: "الجلسات النشطة", sessionsHint: "عرض وإدارة الجلسات النشطة لحسابك.",
    devices: "الأجهزة الموثوقة", devicesHint: "إدارة الأجهزة التي تثق بها وتستخدمها لتسجيل الدخول.",
    recovery: "استعادة الحساب", recoveryHint: "إعداد طرق استعادة الحساب في حال فقدان الوصول إليه.",
    password: "تغيير كلمة المرور", passwordHint: "تحديث كلمة المرور الخاصة بحسابك.",
    twoFactor: "تفعيل التحقق بخطوتين", twoFactorHint: "زيادة أمان حسابك عن طريق التحقق بخطوتين.",
    notifications: "الإشعارات", notificationsHint: "اختر نوع الإشعارات التي ترغب في استلامها.",
    enableNotifications: "تفعيل الإشعارات", enableNotificationsHint: "استلم إشعارات حول الرسائل والطلبات والفرص والتحديثات المهمة.",
    enabled: "مفعل", disabled: "غير مفعل", localToggle: "تبديل للمعاينة فقط",
    account: "إعدادات الحساب", accountHint: "إدارة حالة حسابك على المنصة.",
    suspend: "إيقاف الحساب مؤقتًا", suspendHint: "يمكنك إيقاف حسابك مؤقتًا وإعادة تفعيله لاحقًا.",
    delete: "حذف الحساب", deleteHint: "سيتم حذف بيانات حسابك نهائيًا ولا يمكن استرجاعها.",
    unavailable: "هذا الإجراء للعرض فقط في المعاينة. لم يتم تغيير أي إعداد أمان أو إيقاف أو حذف أي حساب.",
  },
  en: {
    title: "Settings", subtitle: "Manage your account, personal information, notifications, privacy and security.",
    preview: "Preview only — changes here do not affect your real account.",
    personal: "Personal information", personalHint: "Manage your personal details and account contact information.",
    name: "Display name", username: "Username", usernameHint: "Your username will appear in your profile link.",
    email: "Email address", optional: "Optional", phone: "Phone number", secondaryPhone: "Additional phone number",
    addPhone: "Add another phone", removePhone: "Remove additional phone", save: "Save changes",
    saved: "Changes saved in this preview only. Your real account has not changed.", phoneError: "Enter a valid phone number and select its country.",
    security: "Privacy & security", securityHint: "Keep your account and personal information secure.",
    login: "Sign-in methods", loginHint: "Illustrative states only; no accounts are connected through this preview.",
    connected: "Connected", disconnected: "Not connected",
    sessions: "Active sessions", sessionsHint: "View and manage your active account sessions.",
    devices: "Trusted devices", devicesHint: "Manage devices you trust and use to sign in.",
    recovery: "Account recovery", recoveryHint: "Set up ways to recover your account if you lose access.",
    password: "Change password", passwordHint: "Update your account password.",
    twoFactor: "Enable two-step verification", twoFactorHint: "Add account security with two-step verification.",
    notifications: "Notifications", notificationsHint: "Choose the notifications you would like to receive.",
    enableNotifications: "Enable notifications", enableNotificationsHint: "Receive notifications about messages, requests, opportunities and important updates.",
    enabled: "Enabled", disabled: "Disabled", localToggle: "Preview toggle only",
    account: "Account settings", accountHint: "Manage your account status on the platform.",
    suspend: "Temporarily suspend account", suspendHint: "You can pause your account and reactivate it later.",
    delete: "Delete account", deleteHint: "Your account data would be permanently deleted and could not be recovered.",
    unavailable: "This action is a visual preview only. No security settings were changed and no account was suspended or deleted.",
  },
};
